# Generated by Django 2.0.5 on 2018-07-01 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_by', models.CharField(help_text='Department/Section/Club/others name', max_length=250, verbose_name='Program Offered by')),
                ('by', models.CharField(max_length=100, verbose_name='Person Responsible')),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width')),
                ('designation', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=500, verbose_name='Program Name')),
                ('venue', models.CharField(max_length=100)),
                ('chief', models.CharField(max_length=100, verbose_name='Chief Guest')),
                ('objective', models.TextField(verbose_name='Objectives of the Program')),
                ('start', models.DateTimeField(verbose_name='Start Time')),
                ('end', models.DateTimeField(verbose_name='End Time')),
                ('target', models.CharField(max_length=100, verbose_name='Target Audience')),
                ('number', models.PositiveIntegerField(default=50, verbose_name='Expected Number')),
                ('outcome', models.TextField(blank=True, help_text='Mention How the Intended Benefit of the Program will be Achieved', null=True, verbose_name='Object Outcome of the Event')),
                ('approval', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Program Approval')),
                ('booking', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Venue Booking')),
                ('reception', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Guest Reception')),
                ('parking', models.CharField(blank=True, help_text='Responsible person(s) name with mobile number', max_length=100, null=True, verbose_name='Car Parking')),
                ('it', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='IT Support')),
                ('banner', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Banner Text & Size')),
                ('security', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True)),
                ('public_relation', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Public Relation')),
                ('press', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Press Release & Website Text')),
                ('recording', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Video Recording')),
                ('tv', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Campus TV')),
                ('decoration', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Venue Decoration')),
                ('supervision', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Cleaning Supervision')),
                ('Refreshment', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True)),
                ('support', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Staff Support')),
                ('transport', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Transport Booking')),
                ('extsupport', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Extra Support from Outside')),
                ('others', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Others Requirement')),
                ('master', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Master of Ceremonies')),
                ('outline', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Program Outline & Sequence Confirmed')),
                ('training', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Volunteers & Training')),
                ('budget', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Budget Source')),
                ('contribution', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Departmental Contribution')),
                ('sponsor', models.CharField(blank=True, help_text="Responsible person's name with mobile number", max_length=100, null=True, verbose_name='Sponsor Contribution')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-update'],
            },
        ),
    ]
