# Generated by Django 2.0.5 on 2018-07-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swehome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approved',
        ),
    ]
