# Generated by Django 2.0.5 on 2018-07-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swehome', '0002_remove_event_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
