# Generated by Django 2.0.5 on 2018-07-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swehome', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
