# Generated by Django 2.0.5 on 2018-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swehome', '0005_auto_20180715_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('Recent', 'Recent'), ('OnGoing', 'OnGoing'), ('UpComing', 'UpComing')], max_length=10, null=True),
        ),
    ]
