# Generated by Django 2.0.5 on 2018-07-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0003_auto_20180716_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationpost',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
